# Generated by Django 5.1.6 on 2025-03-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='file.jpg', upload_to=''),
        ),
    ]
